pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"

    }

    environment {
 
        SNAP_REPO = 'vprofile-snapshot'
        NEXUS_USER = 'admin'
        NEXUS_PASS = 'Sonarqube@440'
        RELEASE_REPO = 'vprofile-release'
        CENTRAL_REPO = 'vpro-maven-central'
        NEXUSIP = '10.0.9.122'
        NEXUSPORT = '8081'
        NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'
        SONARSERVER = 'sonarserver'
        SONARSCANNER = 'sonarscanner'
        registryCredential = 'ecr:ap-northeast-1:awscreds'
        appRegistry = '299119787392.dkr.ecr.ap-northeast-1.amazonaws.com/vprofileappimg'
        vprofileRegistry = "https://299119787392.dkr.ecr.ap-northeast-1.amazonaws.com"
        CHART_PATH = 'helm/vprofilecharts'
        NAMESPACE = 'default'
        RELEASE_NAME = 'kubeproj-stack'
        EKS_CLUSTER = 'vprofile'
        AWS_REGION = 'ap-northeast-1' 

    }

    stages {
        stage('Build'){
            steps {
                sh 'mvn -s settings.xml -DskipTests install'
            }
            post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }



        stage('UNIT TEST'){
            steps {
                sh 'mvn -s settings.xml test'
            }
        }

        stage('CHECKSTYLE CodeAnalysis'){
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle' 
            }
        }

        stage('SONARQUBE ANALYSIS') {
 
            environment {
                scannerHome = tool "${SONARSCANNER}"
            }

            steps {
               withSonarQubeEnv("${SONARSERVER}") {
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                        -Dsonar.projectName=vprofile-repo \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.sources=src/ \
                        -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                        -Dsonar.junit.reportsPath=target/surefire-reports/ \
                        -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                        -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''

                }
            }
        }
        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('upload artifact') {
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
                    groupId: 'QA',
                    version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                    repository: "${RELEASE_REPO}",
                    credentialsId: "${NEXUS_LOGIN}",
                    artifacts: [
                      [artifactId: 'vproapp',
                       classifier: '',
                       file: 'target/vprofile-v2.war',
                       type: 'jar']
                    ]
                )
            }
        }

        stage('Build App Image') {
            steps {
                script {
                    dockerImage = docker.build( appRegistry + ":$BUILD_NUMBER", "./Docker-files/app/multistage/")

                }
            }
        }

        stage('Upload App Image') {
            steps {
                script {
                    docker.withRegistry( vprofileRegistry, registryCredential ) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
 
                }
            }
        }


        stage('Install kubectl') {
            steps {
                sh '''
                mkdir -p $JENKINS_BIN
                curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                chmod +x kubectl
                mv kubectl $JENKINS_BIN/
                echo "export PATH=$JENKINS_BIN:$PATH" >> ~/.bashrc
                export PATH=$JENKINS_BIN:$PATH
                '''
            }
        }

        stage('Install Helm') {
            steps {
                sh '''
                mkdir -p $JENKINS_BIN
                curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
                chmod 700 get_helm.sh
                ./get_helm.sh --no-sudo --bin $JENKINS_BIN
                echo "export PATH=$JENKINS_BIN:$PATH" >> ~/.bashrc
                export PATH=$JENKINS_BIN:$PATH
                '''
            }
        }

        stage('Configure kubectl for EKS') {
            steps {
                sh '''
                export PATH=$JENKINS_BIN:$PATH
                aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER
                '''
            }
        }

        stage('Verify Kubernetes Connection') {
            steps {
                sh '''
                export PATH=$JENKINS_BIN:$PATH
                kubectl get nodes
                '''
            }
        }

        stage('Deploy Helm Chart') {
            steps {
                sh '''
                export PATH=$JENKINS_BIN:$PATH
                helm upgrade --install $RELEASE_NAME $CHART_PATH \
                --namespace $NAMESPACE \
                --set appimage=$appRegistry,apptag=$BUILD_NUMBER
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                sh '''
                export PATH=$JENKINS_BIN:$PATH
                kubectl get pods -n $NAMESPACE
                '''
            }
        }
    }

}
